# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-26 08:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='word',
            name='size',
            field=models.IntegerField(default=0.8),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='word',
            name='zindex',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
