# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-26 08:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_auto_20160526_0835'),
    ]

    operations = [
        migrations.AlterField(
            model_name='word',
            name='size',
            field=models.FloatField(),
        ),
    ]
